### ISSUE TITLE
Use private network addresses on documentation

### ISSUE THREAD

**Issue by StrongestNumber9** [teragrep/dkr_01#13]
The ip 1.2.3.4 used in tests is publicly routable, https://whatismyipaddress.com/ip/1.2.3.4 and trying to connect and/or send data there is not advisable. Use something like 127.0.0.1 instead.

```sh
    --log-opt relpHostname=1.2.3.4 \
```

and

```sh
        relpHostname: "1.2.3.4"
```

**Comment by eemhu** [comment]
replaced public IPs with 127.0.0.1
